#!/bin/sh
wayland_envs=`tr '\0' '\n' < /proc/$(pgrep --uid $(id --user) --newest sway)/environ | grep -E 'WAY|XDG_R' | xargs`
if [ "$wayland_envs" = "" ]; then
	exit 1
else
	export $wayland_envs LANG=en_US.UTF-8
   	foot --server
fi
