#!/bin/bash
wayland_envs=`tr '\0' '\n' < /proc/$(pgrep --uid $(id --user) --newest sway)/environ | grep -E 'WAY|XDG_R|DBUS_SESS' | xargs`
if [[ -z $wayland_envs ]]; then
	exit 1
else
	export $wayland_envs
	export LANG=en_US.UTF-8
	exec foot --server
fi
